---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: my_vpc
    cidr_block: "{{ cidr_block }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: vpc

- name: Create Subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ cidr }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: subnet

- name: Create Security Group
  amazon.aws.ec2_group:
    name: my_security_group
    description: Allow HTTP and SSH traffic
    vpc_id: "{{ vpc.vpc.id }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ cidr_ip }}"
      - proto: tcp
        from_port: "{{ httpd_listen_port }}"
        to_port: "{{ httpd_listen_port }}"
        cidr_ip: "{{ cidr_ip }}"
  register: security_group

- name: Launch EC2 instances
  amazon.aws.ec2_instance:
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami }}" # Replace with your desired AMI
    key_name: "{{ key_name }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}" # Replace with your SSH key pair name
    count: 2
    wait: true
    assign_public_ip: true
    aws_region: "{{ region }}"
    subnet_id: "{{ subnet.subnet.id }}"
    security_group: "{{ security_group.group_id }}"
    tags:
      Name: "webserver"
  register: ec2_instances
  
