---
- name: Install OpenSSL
  yum:
    name: openssl
    state: present

- name: Generate self-signed SSL certificate
  openssl_certificate:
    path: "{{ ssl_certificate_path }}"
    privatekey_path: "{{ ssl_certificate_key_path }}"
    provider: selfsigned
